logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(%5p) %clr(${PID}){magenta} --- [%15.15t] %clr(%-40.40logger{39}){cyan} : %m %clr(%mdc){magenta} %n%wEx"
#  level:
#    root: debug
budget-analyzer:
  db:
    liquibase-changelog: classpath:db/changelog/changelog-master.xml
spring:
  rsocket:
    server:
      mapping-path: /rsocket
      transport: websocket
  kafka:
    consumer:
      group-id: ru.wtrn.dashboard
